apiVersion: v1
kind: Pod
metadata:
  name: cache
spec:
  containers:
    - name: cache-container
      image: redis:5.0
      resources:
        requests:
          memory: "8Mi"
          cpu: "10m"
        limits: 
          memory: "32Mi"
          cpu: "100m"
      ports: 
      - containerPort: 6379