apiVersion: v1
kind: Service
metadata:
  name: kadai-lb
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8000
      targetPort: 80
      nodePort: 30100
  selector:
    app: web