apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: web-ds
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      containers:
        - name: nginx-container
          image: nginx:stable
          ports:
          - containerPort: 80